### PR TITLE
128.0-2

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by Stebalien** [comment]
I'm not sure if it's a local issue, but I can't seem to run two copies at once. I.e., I'd expect the second `flatpak run io.gitlab.librewolf-community` to simply open a new window but... I'm getting the following errors:

```
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 84: Error: Can't find profile directory.
```

**Comment by lsfxz** [comment]
Yep, can reproduce the issue (and receiving the error).

I have a _hunch_ where to look for the cause, but no guarantees yet. Thanks for the PR and, well, also for testing it. I would've probably missed the issue.

**Comment by Stebalien** [comment]
Yeah, the name has changed to `io.gitlab.firefox.*`.

**Comment by lsfxz** [comment]
> Yeah, the name has changed to `io.gitlab.firefox.*`.

huh, where did you spot that?
(I first thought it might've been the recent [small] change of the `MOZ_APP_REMOTINGNAME`, but that had happened a while ago already, and at least on our end, I don't think we've had any significant changes that should've been the issue).
Might be an upstream change/addition to `toolkit/xre/nsXREDirProvider.cpp` again though, only this time without causing the existing patch to fail.
I'll try to look into it when I'm back on my computer later tonight; sorry for the delay!

**Comment by Stebalien** [comment]
> huh, where did you spot that?

I gave the LibreWolf flatpak full access to my session D-Bus with Flatseal then used D-Spy to find anything firefox/librewolf/mozilla related.

> I'll try to look into it when I'm back on my computer later tonight; sorry for the delay!

No problem! And thanks for maintaining this package!

**Comment by guihkx** [comment]
Can you guys try reproducing the issue on a clean prefix (i.e. by renaming/removing `~/.var/app/io.gitlab.librewolf-community`)?

I've built 128.0 locally, and it's working just fine for me:

image

**Comment by Stebalien** [comment]
@guihkx have you tried calling:

- `flatpak run io.gitlab.librewolf-community`
- In a new terminal window, `flatpak run io.gitlab.librewolf-community -new-window`

?

In my case, that hung until I allowed librewolf to own the `io.gitlab.firefox.*` dbus name.

**Comment by guihkx** [comment]
Thanks for clear reproduction steps. And yeah, it hangs here, too. :/

**Comment by Stebalien** [comment]
It looks like the dbus patch (https://codeberg.org/librewolf/source/src/branch/main/patches/dbus_name.patch) is working correctly but `aProgram` is set to `firefox` instead of `librewolf`.

**Comment by lsfxz** [comment]
Yeah, it's a bit of a mess. Because… this has been (mysteriously) _wrong_ in some places before (opening `about:support` in older versions, for example, will already show `Firefox` as name; same for the `application.ini` – but app-basename and app-name are set properly during building, and work (seemingly) "in other places".
but now, _something_ has changed (upstream though), and it's still unclear what, to me, unfortunately :/

**Comment by Stebalien** [comment]
For _now_, I'd just allow `io.gitlab.firefox.*` in the Flatpak so we can get the release out. Have you filed an upstream LibreWolf bug? I'm not sure where it's supposed to be filed.

**Comment by lsfxz** [comment]
Haven't filed one yet, nope. Good point though; the others might have a better idea what's going on.
(there's only one issue tracker nowadays: https://codeberg.org/librewolf/issues/issues ^^)

Considering _io.gitlab_.firefox.* shouldn't be in use anywhere else, that shouldn't clash with anything else, so I guess that solution would be okay to get the release out, yeah.

**Comment by lsfxz** [comment]
That seems to do the trick for now.

**Comment by lsfxz** [comment]
Cause is probably https://github.com/mozilla/gecko-dev/commit/25028520b611bab175ade3e00a42b5b454562803
(which is probably why it didn't cause issues before even with seemingly broken app-/basename)

Time for me to open an issue I guess, unless I find a way to fix it right away ^^

**Pull request merged**
