### PR TITLE
add libnotify

### LINKED ISSUE #7: Native notifications don't work
LibreWolf Flatpak uses legacy notifications, which on KDE Wayland looks like this (it opens in the center of the screen):

image

In the official Firefox flatpak notifications work properly.

### PR DESCRIPTION
**Pull request by sentriz**
fixes #7
fixes https://gitlab.com/librewolf-community/browser/flatpak/-/issues/32

the snippet was stolen from [here](https://github.com/flathub/com.github.micahflee.torbrowser-launcher/pull/50) 

and seems to work for me:

image

### CODE REVIEW

**Comment by sentriz** [comment]
is it possible to get the flathub bot to start a test build?

**Comment by sentriz** [comment]
bot, build

**Comment by sentriz** [comment]
it works! 
image

**Comment by lsfxz** [comment]
Oh, very nice – thanks a lot!

Doesn't seem to break anything, so let's merge this! :)

**Pull request merged**
